spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: mscourse-eureka-user
      password: rouarcsuueeess-mke-r

server:
  port: 8761

eureke:
  client:
    register-with-eureka: false
    fetch-registry: false

